### ISSUE TITLE
Hi Is it not good if SME create Step by Step Deployment Document

### ISSUE THREAD

**Issue by bipeensinha** [bipeensinha/CTRLSPrj#1]
Hi All,

This is John , New Team member . I face challenge
![GitRepo](https://user-images.githubusercontent.com/49720823/188783107-977272f2-5474-4ebb-be87-6aefab747e1a.jpg)
 while implement this feature , can we create step by step document.

@sameer0016 your input please.  @rahul242k just have your say.

**Comment by tsharithanaidu** [comment]
nice thought

**Comment by Sairam1123** [comment]
John, We can do that, I'm on it.

**Comment by Ihzan-k123** [comment]
thanks for assigning.

**Comment by bipeensinha** [comment]
![cadbury-dairy-milk-silk-chocolate-bar-150-g-product-images-o490659554-p490659554-1-202203170400](https://user-images.githubusercontent.com/49720823/188783605-95569971-f948-4e64-a47a-0429f5580ab6.jpg)
